### ISSUE TITLE
Deploying via Dockerfile results in a `raise ArgumentError, "Secret should not be nil." unless secret` exception

### ISSUE THREAD

**Issue by bradgessler** [ankane/mailkick#75]
When deploying Mailkick to a Dockerfile, the following error occurs:

```
Step 12/23 : RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
 ---> Running in af9a7e2374ac
bin/rails aborted!
ArgumentError: Secret should not be nil. (ArgumentError)

      raise ArgumentError, "Secret should not be nil." unless secret
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/message_verifier.rb:154:in `initialize'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/messages/rotator.rb:7:in `initialize'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/messages/rotator.rb:45:in `new'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/messages/rotator.rb:45:in `build_rotation'
/rails/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/messages/rotator.rb:15:in `rotate'
/rails/vendor/bundle/ruby/3.2.0/gems/mailkick-1.2.1/lib/mailkick/engine.rb:23:in `block in <class:Engine>'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:60:in `run_initializers'
/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:423:in `initialize!'
/rails/config/environment.rb:5:in `<main>'
```

The mailkick initializer assumes it will get a secret key or base, but build environments don't have the secrets that are assumed to be present by the initializer.

To recreate, run the following on any machine with Docker:

```
rails new mail-app
bundle add mailkick
bundle add dockerfile-rails --optimistic --group development
bin/rails generate dockerfile 
docker build .
```

**Comment by bradgessler** [comment]
FYI @lucianghinda when this issue is closed your app should be deployable.

**Comment by ankane** [comment]
Hi @bradgessler, thanks for reporting. Fixed in the commit above.
